# Environment
env:
  env_name: PatrolEnvGrid
  num_envs: 20

# collector
collector:
  frames_per_batch: 4000
  total_frames: 10_000_000

# logger
logger:
  backend: wandb
  project_name: patrol_pixels
  group_name: null
  exp_name: PPO
  test_interval: 100_000
  num_test_episodes: 1
  mode: online  

# Optim
optim:
  lr: 2.5e-4
  eps: 1.0e-6
  weight_decay: 0.01
  max_grad_norm: 10.0
  anneal_lr: False

# loss
loss:
  gamma: 0.99
  mini_batch_size: 4000
  ppo_epochs: 20
  gae_lambda: 0.95
  clip_epsilon: 0.2
  anneal_clip_epsilon: False
  critic_coef: 1.0
  entropy_coef: 0.02
  loss_critic_type: l2

model_save:
  save_interval: 100_000
  experiment_name: e3