# Environment
env:
  env_name: PatrolEnvGrid
  num_envs: 600

# collector
collector:
  frames_per_batch: 12_000
  total_frames: 100_000_000

# logger
logger:
  backend: wandb
  project_name: torchrl_example_ppo
  group_name: null
  exp_name: PPO
  test_interval: 1_000_000
  num_test_episodes: 1
  mode: online  

# Optim
optim:
  lr: 2.5e-4
  eps: 1.0e-6
  weight_decay: 0.01
  max_grad_norm: 10.0
  anneal_lr: True

# loss
loss:
  gamma: 0.99
  mini_batch_size: 4000
  ppo_epochs: 10
  gae_lambda: 0.95
  clip_epsilon: 0.1
  anneal_clip_epsilon: True
  critic_coef: 1.0
  entropy_coef: 0.01
  loss_critic_type: l2

model_save:
  save_interval: 1_000_000
  experiment_name: e3