# task config
task: heading

# simulation config
sim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 1000             # episode length: 200s
altitude_limit: 2000
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# (latitude, longitude, altitude)
battle_field_origin: [59.3, 18.0, 0.0]

# aircraft config
aircraft_configs: {
  A0100: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 18.0,
      ic_lat_geod_deg: 59.3,
      ic_h_sl_ft: 16404,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    }
  }
}


# reward config
AltitudeReward_safe_altitude: 2.0
AltitudeReward_danger_altitude: 1.5
AltitudeReward_Kv: 0.2
