# task config
task: heading

# simulation config
sim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 10_000            # episode length: 200s
altitude_limit: 100
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# (latitude, longitude, altitude)
battle_field_origin: [56.98033, 14.07798, 0.0]

# aircraft config
aircraft_configs: {
  A0100: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 14.07798,
      ic_lat_geod_deg: 56.98033,
      ic_h_sl_ft: 16404,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    }
  }
}


# reward config
SafeAltitudeReward_safe_altitude: 1.0
SafeAltitudeReward_danger_altitude: 0.5
SafeAltitudeReward_Kv: 0.2
